[package]
name = "lightbox"
version = "0.1.0"
authors = ["Kinnon McAlister <kinnonmcalister@gmail.com>"]
edition = "2018"

[dependencies]
# bluez = "0.1.3"
# async-std = {version = "1.6.2", features = ["unstable"]}
# async-ctrlc = "1.2.0"

blinkt = "0.5"
ctrlc = "3.1.7"
rodio = "0.12"
cpal = "0.12"
microfft = { version = "0.3.0", default-features = false, features = ["maxn-256"]}
average = "0.10"
thread-priority = "0.2.0"

# Waiting on https://github.com/RustAudio/cpal/issues/473
[patch.crates-io]
rodio = {git = "https://github.com/RustAudio/rodio"}
cpal = {git = "https://github.com/RustAudio/cpal"}

[patch.'https://github.com/eloc3147/rodio/']
cpal = {git = "https://github.com/RustAudio/cpal"}
